<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Investimentos.Application.Commands\Investimentos.Application.Commands.csproj" />
    <ProjectReference Include="..\Investimentos.Application.Contracts\Investimentos.Application.Contracts.csproj" />
    <ProjectReference Include="..\Investimentos.Application.Queries\Investimentos.Application.Queries.csproj" />
    <ProjectReference Include="..\Investimentos.Infrastructure.Repository\Investimentos.Infrastructure.DataStore.csproj" />
  </ItemGroup>

</Project>
